name: Deploy

on:
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: twomorrowstech/deploy-gh-pages-from-private-repo-action@v1
        with:
          repo: test-jekyll
          run-id: 8273256724
          github-token: ${{ secrets.TEST_JEKYLL_ACTION_TOKEN }}
    
          
    
