name: Jekyll Site Deploy

on:
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:

# permissions:
#   actions: read
  # pages: write
  # id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: github-pages
          repo: jonsmorrow/test-jekyll
          
    
