name: Jekyll Site Deploy

on:
  repository_dispatch:
    types: [trigger-deploy]
  workflow_dispatch:

permissions:
#   actions: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Download artifact
      #   id: download-artifact
      #   uses: dawidd6/action-download-artifact@v3
      #   with:
      #     github_token: ${{secrets.TEST_JEKYLL_ACTION_TOKEN}}
      #     name: github-pages
      #     workflow: main.yml
      #     repo: jonsmorrow/test-jekyll
      # - name: LS
      #   run: ls -al .
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{secrets.TEST_JEKYLL_ACTION_TOKEN}}
          repository: jonsmorrow/test-jekyll
          name: github-pages
      - name: Display structure of downloaded files
        run: ls -R .
      - name: ECHO
        run: echo $ACTIONS_RESULTS_URL
      # - name: Setup Pages
      #   uses: actions/configure-pages@v3
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./artifact.tar
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
          
    
